config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'admin_login/' => 'admin_login#index'
  post 'admin_login/login' => 'admin_login#login'
  post 'admin_login/logout' => 'admin_login#logout'

  namespace :manage do
    get :table_list
    get :column_list
  end

  resources :shops do
    patch 'delete', :on => :member
  end

  resources :tips do
    patch 'delete', :on => :member
  end

  resources :tip_genres

  resources :contacts

  resources :genre_tags
end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  rate        :float(24)
#  area        :string(255)
#  address     :string(255)
#  latitude    :float(24)
#  longitude   :float(24)
#  url         :string(255)
#  comment     :string(255)
#  detail      :text(65535)
#  image1      :string(255)
#  image2      :string(255)
#  image3      :string(255)
#  delete_flag :boolean          default("0")
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Shop < ApplicationRecord
  has_many :shops_genre_tags
  has_many :genre_tags, :through => :shops_genre_tags

  accepts_nested_attributes_for :genre_tags

  mount_uploader :image1, ImageUploader
  mount_uploader :image2, ImageUploader
  mount_uploader :image3, ImageUploader
  geocoded_by :address
  after_validation :geocode

  attr_accessor :new_area, :remove_image1, :remove_image2, :remove_image3

  validates :name, presence: true
  validates :rate, presence: true, numericality: true
  validates :area, presence: true, if: :new_area_blank?

  before_update do
    self.image1 = "" if remove_image1.to_i.nonzero?
    self.image2 = "" if remove_image2.to_i.nonzero?
    self.image3 = "" if remove_image3.to_i.nonzero?
  end

  def new_area_blank?
    new_area.blank?
  end

  def image1_filename
    name_array = self.image1.to_s.split('/')
    filename = name_array[name_array.length - 1]
  end

  def image2_filename
    name_array = self.image2.to_s.split('/')
    filename = name_array[name_array.length - 1]
  end

  def image3_filename
    name_array = self.image3.to_s.split('/')
    filename = name_array[name_array.length - 1]
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  require 'dropbox_sdk'
  before_action :set_shop, only: %w(edit update delete)

  def index
    @q = Shop.ransack(params[:q])
    shops = @q.result.where(delete_flag: false)
    @shops = shops.page(params[:page]).order(created_at: :desc)
    @shops_genre_tags = ShopsGenreTag.where(shop_id: @shops.ids)
    @genre_tags = GenreTag.where(id: @shops_genre_tags.map{|item| item.genre_tag_id})
  end

  def new
    @shop = Shop.new
    @rate_values = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    @areas = Shop.select(:area).uniq
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.valid?
      @shop.area = @shop.new_area if @shop.new_area.present?
      @shop.save
      redirect_to shops_path
    else
      @rate_values = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
      @areas = Shop.select(:area).uniq
      render 'new'
    end
  end

  def show
    @shop = Shop.find(params[:id])
    genre_tag_ids = ShopsGenreTag.where(shop_id: @shop.id).map {|item| item.genre_tag_id}
    @genre_tag_names = GenreTag.where(id: genre_tag_ids).map {|item| item.tag_name}
    # 画像パスを取得(本番環境ではDropboxから取得)
    client = new_dropbox_client if Rails.env.production?
    @image1_path = (Rails.env.production?) ? client.media(@shop.image1_filename)['url'] : @shop.image1.url if @shop.image1.url.present?
    @image2_path = (Rails.env.production?) ? client.media(@shop.image2_filename)['url'] : @shop.image2.url if @shop.image2.url.present?
    @image3_path = (Rails.env.production?) ? client.media(@shop.image3_filename)['url'] : @shop.image3.url if @shop.image3.url.present?

    # サイドバーの情報を取得
    @all_shop_count = Shop.where(delete_flag: false).where.not(latitude: nil, longitude:nil).count
    @area_search_info = get_area_search_info
    @genre_tag_search_info = get_genre_tag_search_info

    @map = Gmaps4rails.build_markers(@shop) do |s, marker|
      marker.lat s.latitude
      marker.lng s.longitude
      marker.infowindow render_to_string(partial: "shops/infowindow", locals: { shop: s })
      marker.json({title: s.name})
    end
  end

  def edit
    @rate_values = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    @areas = Shop.select(:area).uniq
  end

  def update
    if @shop.update(shop_params)
      @shop.area = @shop.new_area if @shop.new_area.present?
      @shop.save
      redirect_to shops_path
    else
      @rate_values = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
      @areas = Shop.select(:area).uniq
      render 'edit'
    end
  end

  def delete
    if @shop.update_attribute(:delete_flag, true)
      redirect_to shops_path
    else
      redirect_to shops_path, alert: '削除に失敗しました'
    end
  end

  private

    def shop_params
      params.require(:shop).permit(:name, :rate, :area, :new_area, :address, :url, :comment, :detail, :image1, :image2, :image3, :remove_image1, :remove_image2, :remove_image3 ,{ :genre_tag_ids=> [] })
    end

    def set_shop
      @shop = Shop.find(params[:id])
    end

    # 地域検索の情報(地域名、店舗数)を取得するメソッド
    def get_area_search_info
      area_search_info = {}
      areas = Shop.select(:area).uniq
      areas.each do |area|
        shop_count = Shop.where(delete_flag: false, area: area.area).count
        area_search_info[area.area] = shop_count
      end
      area_search_info.sort {|(k1, v1), (k2, v2)| v2 <=> v1 }
      area_search_info
    end

    # ジャンル検索の情報(ジャンル名、店舗数)を取得するメソッド
    def get_genre_tag_search_info
      genre_tag_search_info = {}
      genre_tags = GenreTag.all
      genre_tags.each do |genre_tag|
        shop_count = ShopsGenreTag.where(genre_tag_id: genre_tag.id).count
        genre_tag_search_info[genre_tag.tag_name] = shop_count
      end
      genre_tag_search_info
    end
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "店名", class: 'required' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :rate, "評価", class: 'required' %>
    <%= f.select :rate, @rate_values.map{|t| [t, t]}, { prompt: "選択してください" }, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :genre_tags, "ジャンル" %><br/>
    <%= collection_check_boxes(:shop, :genre_tag_ids, GenreTag.all, :id, :tag_name ) do |t|  %>
      <% t.label { t.check_box + t.text + '　' } %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :area, "地域", class: 'required' %>
    <%= f.select :area, @areas.map{|t| [t.area, t.area]}, { prompt: "選択してください" }, { class: 'form-control' } %>
    <div>( 新たに追加する場合↓ )</div>
    <%= f.text_field :new_area, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address, "住所" %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :url, "URL"%>
    <%= f.text_field :url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :comment, "特徴"%>
    <%= f.text_field :comment, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :detail, "詳細"%>
    <%= f.text_area :detail, class: 'form-control', size: "100x10" %>
  </div>

  <div class="form-group">
    <%= f.label :image1, "画像1" %>
    <% if @shop.image1? %>
      <%= image_tag @shop.image1.url, class: 'thumbnail' %>
      <label>
        <%= f.check_box :remove_image1 %>
        画像1を削除
      </label>
    <% end %>
    <%= f.file_field :image1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image2, "画像2" %>
    <% if @shop.image2? %>
      <%= image_tag @shop.image2.url, class: 'thumbnail' %>
      <label>
        <%= f.check_box :remove_image2 %>
        画像2を削除
      </label>
    <% end %>
    <%= f.file_field :image2, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image3, "画像3" %>
    <% if @shop.image3? %>
      <%= image_tag @shop.image3.url, class: 'thumbnail' %>
      <label>
        <%= f.check_box :remove_image3 %>
        画像1を削除
      </label>
    <% end %>
    <%= f.file_field :image3, class: 'form-control' %>
  </div>

  <%= f.submit "登録", class: "btn btn-primary" %>
  <%= link_to "戻る", shops_path, class: "btn btn-default" %>
<% end %>

app/views/shops/_infowindow.html.erb
<h2><%= shop.name %></h2>
<%= shop.area %><br>
<%= link_to shop.url, "#{shop.url}" %>

app/views/shops/_search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">検索</div>
  </div>
  <div class="panel-body">
    <%= search_form_for @q do |f| %>
      <div class="row">
        <div class="col-md-12 col-xs-12">
          <div class="form-group">
            <%= f.label :name_cont, "店名" %>
            <%= f.text_field :name_cont, class: "form-control"%>
          </div>
        </div>
        <div class="col-md-12 col-xs-12">
          <div class="form-group">
            <%= f.label :genre_tags_id_in, "ジャンル" %><br/>
            <%= f.collection_check_boxes(:genre_tags_id_in, GenreTag.all, :id, :tag_name ) do |t|  %>
              <% t.label { t.check_box + t.text + '　' } %>
            <% end %>
          </div>
        </div>
        <div class="col-md-12 col-xs-12">
          <div class="form-inline">
            <%= f.label :created_at, "作成日" %>
            <%= f.date_select :created_at_gt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>〜
            <%= f.date_select :created_at_lt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>
          </div>
        </div>
      </div>
      <%= f.submit '検索', class: "btn btn-primary" %>
      <%= link_to 'クリア', shops_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/shops/edit.html.erb
<% if logged_in? %>
  <% set_meta_tags :title => 'SHOP情報編集', :reverse => true %>
  <div class="container">
    <div class="new">
      <h1>編集画面</h1>

      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-xs-12">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/notfound' %>
<% end %>

app/views/shops/index.html.erb
<% if logged_in? %>
  <% set_meta_tags :title => 'Shop一覧', :reverse => true %>
  <div class="container">
    <h1>Shop一覧</h1>

    <%= render 'search' %>

    <%= link_to "新規登録", new_shop_path, class: "btn btn-primary" %>
    <%= link_to "ジャンルを新規登録", new_genre_tag_path, class: "btn btn-success" %><br>

    <%= page_entries_info @shops %><br><%= paginate @shops %>
    <div class="row">
      <table class="table table-bordered table-striped">
        <tr>
          <th width="15%">店舗名</th>
          <th width="10%">評価</th>
          <th width="10%">エリア</th>
          <th width="20%">ジャンル</th>
          <th width="30%">特徴</th>
          <th width="10%">作成日</th>
          <th width="5%">詳細<br>変更<br>削除</th>
        </tr>
        <% @shops.each do |shop| %>
          <tr>
            <td><%= shop.name %></td>
            <td><%= shop.rate %></td>
            <td><%= shop.area %></td>
            <td>
            <% str_list = [] %>
            <% @shops_genre_tags.each do |item| %>
              <% if shop.id == item.shop_id %>
                <% str_list << @genre_tags.find_by(id: item.genre_tag_id).tag_name %>
              <% end %>
            <% end %>
            <%= str_list.join(', ') %>
            </td>
            <td><%= shop.comment %></td>
            <td><%= shop.created_at.year %>年<%= shop.created_at.month %>月<%= shop.created_at.day %>日</td>
            <td>
              <%= link_to "詳細", shop_path(shop) %><br>
              <%= link_to "変更", edit_shop_path(shop) %><br>
              <%= link_to "削除", delete_shop_path(shop), :method => 'patch', data: {confirm: "本当に削除しますか？"}%>
          </tr>
        <% end %>
      </table>
    </div>

    <br><%= paginate @shops %>
  </div>
<% else %>
  <%= render 'layouts/notfound' %>
<% end %>

app/views/shops/new.html.erb
<% if logged_in? %>
  <% set_meta_tags :title => '新規登録(shop)', :reverse => true %>
  <div class="container">
    <h1>新規登録(SHOP)</h1>
    <p><strong style='color: #E00;'>*</strong>が付いているものは必須項目です。</p><br>

    <div class="row">
      <div class="col-md-6 col-md-offset-3 col-xs-12">
        <%= render 'form' %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/notfound' %>
<% end %>

app/views/shops/show.html.erb
<% set_meta_tags :title => 'SHOP詳細', :reverse => true %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-9">
      <div class="shop-show">
        <h2 class="title">
          <%= @shop.name %><br>
          <% rate_value = @shop.rate.to_s %>
          <% rate_value = rate_value.gsub(/[.]/, '-') %>
          <div class="rate rate<%= rate_value %>"></div>
        </h2>
        <div class="body">
          <div class="image-container">
            <% if @shop.image1.url.present? %>
              <div class="image">
                <%= image_tag(@image1_path, class: "shop-image", align: "center") %>
              </div>
            <% end %>
            <% if @shop.image2.url.present? %>
              <div class="image">
                <%= image_tag(@image2_path, class: "shop-image", align: "center") %>
              </div>
            <% end %>
            <% if @shop.image3.url.present? %>
              <div class="image">
                <%= image_tag(@image3_path, class: "shop-image", align: "center") %>
              </div>
            <% end %>
          </div>
          <div class="detail"><%= markdown(@shop.detail).html_safe %></div>
          <div id="map"></div>
          <script type="text/javascript">
              handler = Gmaps.build('Google');
              handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                markers = handler.addMarkers(<%=raw @map.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(15);
              });
          </script>
          <div class="column-name">ジャンル</div>
          <% @genre_tag_names.each do |tag_name| %>
            <span class="shop-tag"><%= tag_name %></span>
          <% end %>
          <div class="column-name">地域</div>
          <%= @shop.area %>
          <div class="column-name">住所</div>
          <%= @shop.address %>
          <div class="column-name">URL</div>
          <%= link_to @shop.url, "#{@shop.url}" %>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= render 'layouts/sidebar' %>
    </div>
  </div>
</div>