config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'admin_login/' => 'admin_login#index'
  post 'admin_login/login' => 'admin_login#login'
  post 'admin_login/logout' => 'admin_login#logout'

  namespace :manage do
    get :table_list
    get :column_list
  end

  resources :shops do
    patch 'delete', :on => :member
  end

  resources :tips do
    patch 'delete', :on => :member
  end

  resources :tip_genres

  resources :contacts

  resources :genre_tags
end

app/models/tip_genre.rb
# == Schema Information
#
# Table name: tip_genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TipGenre < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :tips

  def image_filename
    name_array = self.image.to_s.split('/')
    filename = name_array[name_array.length - 1]
  end
end

app/controllers/tip_genres_controller.rb
class TipGenresController < ApplicationController
  def index
    @tip_genres = TipGenre.all
    # 画像パスを取得(本番環境ではDropboxから取得)
    client = new_dropbox_client if Rails.env.production?
    @image_paths = {}
    @tip_genres.each do |genre|
      image_path = (Rails.env.production?) ? client.media(genre.image_filename)['url'] : genre.image.url if genre.image.url.present?
      @image_paths[genre.id] = image_path
    end
  end

  def new
    @tip_genre = TipGenre.new
  end

  def create
    @tip_genre = TipGenre.new(tip_genre_params)
    if @tip_genre.save
      redirect_to tip_genres_path
    else
      render 'new'
    end
  end

  def show
    @tip_genre = TipGenre.find(params[:id])
    @tips = Tip.where(genre_id: params[:id], delete_flag: false).order(created_at: :desc)
    # 画像パスを取得(本番環境ではDropboxから取得)
    client = new_dropbox_client if Rails.env.production?
    @image_path = (Rails.env.production?) ? client.media(@tip_genre.image_filename)['url'] : @tip_genre.image.url if @tip_genre.image?
  end

  private

    def tip_genre_params
      params.require(:tip_genre).permit(:name, :image, :image_cache)
    end
end

app/views/tip_genres/_form.html.erb
<%= form_for(@tip_genre) do |f| %>
  <%= f.label :name, "Genre"%>
  <%= f.text_field :name, class: 'form-control', required: true %>
  
  <% if @tip_genre.image? %>
    <div class="thumbnail">
      <%= image_tag @tip_genre.image.url %>
    </div>
  <% end %><br>
  <%= f.label :image, "Image" %><br>
  <%= f.file_field :image , required: true %>
  <%= f.hidden_field :image_cache %>

  <%= f.submit "Register", class: "btn btn-primary" %>
  <%= link_to "Back", tip_genres_url, class: "btn btn-default" %>
<% end %>

app/views/tip_genres/index.html.erb
<% set_meta_tags :title => 'ヒント', :reverse => true %>
<div class="tip-genres">
  <div class="container">
    <span><h1 class="title">See tips</h1></span>
    <% @tip_genres.each_with_index do |genre, i| %>
      <% if i % 3 == 0 %>
        <div class="row">
          <div class="col-md-2 col-md-offset-2">
              <a href="/tip_genres/<%= genre.id %>">
                <%= image_tag(@image_paths[genre.id], class: "img-responsive") %>
                <h3 class="genre-caption"><%= genre.name %></h3>
              </a>
          </div>
      <% else %>
          <div class="col-md-2 col-md-offset-1">
              <a href="/tip_genres/<%= genre.id %>">
                <%= image_tag(@image_paths[genre.id], class: "img-responsive") %>
                <h3 class="genre-caption"><%= genre.name %></h3>
              </a>
          </div>
      <% end %>
      <% if i % 3 == 2 || i == @tip_genres.length - 1 %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if logged_in? %>
    <%= link_to 'Add genre', new_tip_genre_url, class: "btn btn-warning btn-lg btn-block genre-btn" %>
    <%= link_to 'Add tip', new_tip_url, class: "btn btn-danger btn-lg btn-block tip-btn" %>
  <% end %>
</div>

app/views/tip_genres/new.html.erb
<% if logged_in? %>
  <% set_meta_tags :title => '新規登録(tip_genre)', :reverse => true %>
  <div class="tip-genres">
    <div class="container">
      <span><h1 class="title">Add genre</h1></span>
      <div class="row">
        <div class="col-md-6 col-md-offset-3" style="color: #fff;">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/notfound' %>
<% end %>

app/views/tip_genres/show.html.erb
<% set_meta_tags :title => "Tips一覧 [#{@tip_genre.name}]", :reverse => true %>
<div class="tip-genres">
  <div class="show">
    <div class="container">
      <div class="title-div">
        <%= image_tag(@image_path, width: '8%') %>
        <span class="title"><strong>Tips [<%= @tip_genre.name %>]</strong></span>
      </div>

      <div class="tips-list">
        <% @tips.each do |tip| %>
          <%= link_to tip.title, tip_path(tip), class: "btn btn-lg btn-block tip-list-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>