config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'admin_login/' => 'admin_login#index'
  post 'admin_login/login' => 'admin_login#login'
  post 'admin_login/logout' => 'admin_login#logout'

  namespace :manage do
    get :table_list
    get :column_list
  end

  resources :shops do
    patch 'delete', :on => :member
  end

  resources :tips do
    patch 'delete', :on => :member
  end

  resources :tip_genres

  resources :contacts

  resources :genre_tags
end

app/models/tip.rb
# == Schema Information
#
# Table name: tips
#
#  id          :integer          not null, primary key
#  genre_id    :integer          default("0"), not null
#  title       :text(65535)
#  detail      :text(65535)
#  delete_flag :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Tip < ApplicationRecord
  belongs_to :tip_genre, foreign_key: "genre_id"
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: %w(edit update delete)

  def index
    @tips = Tip.all
    @tip_genres = TipGenre.order(:id)
  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new(tip_params)
    @tip.delete_flag = false
    if @tip.save
      redirect_to tip_genres_url
    else
      render 'new'
    end
  end

  def show
    @tip = Tip.find(params[:id])
    @tip_genre = TipGenre.find(@tip.genre_id)
    # 画像パスを取得(本番環境ではDropboxから取得)
    client = new_dropbox_client if Rails.env.production?
    @image_path = (Rails.env.production?) ? client.media(@tip_genre.image_filename)['url'] : @tip_genre.image.url if @tip_genre.image.url.present?
  end

  def edit
  end

  def update
    if @tip.update(tip_params)
      redirect_to tip_path(@tip)
    else
      render 'edit'
    end
  end

  def delete
    if @tip.update_attribute(:delete_flag, true)
      redirect_to tip_genre_path(@tip.genre_id)
    else
      redirect_to tip_genre_path(@tip.genre_id), alert: '削除に失敗しました'
    end
  end

  private

    def tip_params
      params.require(:tip).permit(:title, :detail, :genre_id)
    end

    def set_tip
      @tip = Tip.find(params[:id])
    end
end

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <%= f.label :genre_id, "Genre"%>
  <br>
  <%= f.collection_select :genre_id, TipGenre.all, :id, :name, class: 'form-control', required: true, :include_blank => '選択してください' %>
  
  <br><br>
  <%= f.label :title, "Title"%>
  <%= f.text_field :title, class: 'form-control', required: true %>
  
  <br>
  <%= f.label :detail, "Content"%>
  <%= f.text_area :detail, class: 'form-control', required: true, size: "100x10" %>

  <%= f.submit "Register", class: "btn btn-primary" %>
  <%= link_to "Back", tip_genres_url, class: "btn btn-default" %>
<% end %>

app/views/tips/edit.html.erb
<% set_meta_tags :title => '編集(tip)', :reverse => true %>
<div class="tips">
  <div class="container">
    <span><h1 class="title">Edit tip</h1></span>
    <div class="row">
      <div class="col-md-6 col-md-offset-3" style="color: #fff;">
        <div class="form">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tips/new.html.erb
<% if logged_in? %>
  <% set_meta_tags :title => '新規登録(tip)', :reverse => true %>
  <div class="tips">
    <div class="container">
      <span><h1 class="title">Add tip</h1></span>
      <div class="row">
        <div class="col-md-6 col-md-offset-3" style="color: #fff;">
          <div class="form">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'layouts/notfound' %>
<% end %>

app/views/tips/show.html.erb
<% set_meta_tags :title => 'Tip', :reverse => true %>
<div class="show">
  <div class="genre-div">
    <%= image_tag(@image_path, width: '3%') %>
    <span class="genre-name"><%= @tip_genre.name %></span>
  </div>

  <div class="tip-show-title">
    <h3><%= @tip.title %></h3>
  </div>

  <div class="content">
    <%= markdown(@tip.detail).html_safe %>
  </div>

  <div class="btns">
    <%= link_to "Remove", delete_tip_path(@tip), class: "btn btn-danger", :method => 'patch', data: {confirm: "本当に削除しますか？"} %>
    <%= link_to "Edit", edit_tip_path(@tip), class: "btn btn-warning" %>
    <%= link_to "Back", tip_genre_path(@tip_genre), class: "btn btn-default" %>
  </div>
</div>