config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'admin_login/' => 'admin_login#index'
  post 'admin_login/login' => 'admin_login#login'
  post 'admin_login/logout' => 'admin_login#logout'

  namespace :manage do
    get :table_list
    get :column_list
  end

  resources :shops do
    patch 'delete', :on => :member
  end

  resources :tips do
    patch 'delete', :on => :member
  end

  resources :tip_genres

  resources :contacts

  resources :genre_tags
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav">
          <li><%= link_to "HOME", root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "TABLES", manage_table_list_path %></li>
            <li><%= link_to "SHOPS", shops_path %></li>
            <li><%= link_to "TIPS", tip_genres_path %></li>
          <% end %>
          <li><%= link_to "CONTACT", new_contact_path %></li>
        </ul>
      </nav>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar">
    <div class="container">
      <% if logged_in? %>
        <%= button_to 'Logout', admin_login_logout_path, class: 'btn btn-warning logout-button' %>
      <% end %>
      <div class="main-title">
        <a href="/"><h1>HUMNAVI</h1></a>
      </div>
      <% if logged_in? %>
        <nav>
          <ul class="nav navbar-nav">
            <li><%= link_to "TABLES", manage_table_list_path %></li>
            <li><%= link_to "SHOPS", shops_path %></li>
            <li><%= link_to "TIPS", tip_genres_path %></li>
            <li><%= link_to "CONTACT_MANAGE", contacts_path %></li>
          </ul>
        </nav>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_notfound.html.erb
<h3 class="notfound">
  このページは存在しません。以下のリンクからトップページへ戻ってください。<br><br>
  <%= link_to 'トップページ', root_path %>
</h3>

app/views/layouts/_sidebar.html.erb
<div id ="sidebar-area" class="sidebar">
  <!-- エリアごとの検索用 -->
  <h3 class="sidebar-title"><a href="/"><span class="glyphicon glyphicon-map-marker"></span> エリア</a></h3>
  <div id="sidebar-area-content">
    <% @area_search_info.each do |shop_hash| %>
      <a href="/?area=<%= shop_hash.first %>">
        <div class="column">
          <%= shop_hash.first %> (<%= shop_hash.second %>)
        </div>
      </a>
    <% end %>
  </div>
</div>
<div id ="sidebar-genre" class="sidebar">
  <!-- ジャンルごとの検索用 -->
  <h3 class="sidebar-title"><a href="/"><span class="glyphicon glyphicon-cutlery"></span> ジャンル</a></h3>
  <div id="sidebar-genre-content">
    <% @genre_tag_search_info.each do |genre_info| %>
      <a href="/?genre_tag=<%= genre_info.first %>">
        <div class="column">
          <%= genre_info.first %> (<%= genre_info.second %>)
        </div>
      </a>
    <% end %>
  </div>
</div>

<!-- アフェリエイト -->
<!-- pcページ -->
<% if !is_sp_device? %>
  <div class="affiliate-list">
    <div class="affiliate-item">
      <a href="https://px.a8.net/svt/ejp?a8mat=2TL1JG+7DJCKY+3NWC+631SX" target="_blank" rel="nofollow">
        <img border="0" width="250" height="250" alt="" src="https://www24.a8.net/svt/bgt?aid=170622988446&wid=001&eno=01&mid=s00000017094001022000&mc=1">
      </a>
      <img border="0" width="1" height="1" src="https://www15.a8.net/0.gif?a8mat=2TL1JG+7DJCKY+3NWC+631SX" alt="">
    </div>
    <div class="affiliate-item">
      <a href="https://px.a8.net/svt/ejp?a8mat=2TL1JG+7YDIR6+3PFM+5ZMCH" target="_blank" rel="nofollow">
      <img border="0" width="250" height="250" alt="" src="https://www25.a8.net/svt/bgt?aid=170622988481&wid=001&eno=01&mid=s00000017293001006000&mc=1"></a>
      <img border="0" width="1" height="1" src="https://www18.a8.net/0.gif?a8mat=2TL1JG+7YDIR6+3PFM+5ZMCH" alt="">
    </div>
    <div class="affiliate-item">
      <a href="https://px.a8.net/svt/ejp?a8mat=2TL0RO+3VBGC2+1YGO+6BEQ9" target="_blank" rel="nofollow">
        <img border="0" width="250" height="250" alt="" src="https://www29.a8.net/svt/bgt?aid=170621988234&wid=001&eno=01&mid=s00000009132001061000&mc=1">
      </a>
      <img border="0" width="1" height="1" src="https://www10.a8.net/0.gif?a8mat=2TL0RO+3VBGC2+1YGO+6BEQ9" alt="">
    </div>
  </div>
<% else %>
<!-- spページ -->
<div class="affiliate-list-sp">
  <div class="affiliate-item-sp col-xs-4">
    <a href="https://px.a8.net/svt/ejp?a8mat=2TL1JG+7DJCKY+3NWC+631SX" target="_blank" rel="nofollow">
      <img border="0" width="210" height="210" alt="" src="https://www24.a8.net/svt/bgt?aid=170622988446&wid=001&eno=01&mid=s00000017094001022000&mc=1">
    </a>
    <img border="0" width="1" height="1" src="https://www15.a8.net/0.gif?a8mat=2TL1JG+7DJCKY+3NWC+631SX" alt="">
  </div>
  <div class="affiliate-item-sp col-xs-4">
    <a href="https://px.a8.net/svt/ejp?a8mat=2TL1JG+7YDIR6+3PFM+5ZMCH" target="_blank" rel="nofollow">
    <img border="0" width="210" height="210" alt="" src="https://www25.a8.net/svt/bgt?aid=170622988481&wid=001&eno=01&mid=s00000017293001006000&mc=1"></a>
    <img border="0" width="1" height="1" src="https://www18.a8.net/0.gif?a8mat=2TL1JG+7YDIR6+3PFM+5ZMCH" alt="">
  </div>
  <div class="affiliate-item-sp col-xs-4">
    <a href="https://px.a8.net/svt/ejp?a8mat=2TL0RO+3VBGC2+1YGO+6BEQ9" target="_blank" rel="nofollow">
      <img border="0" width="210" height="210" alt="" src="https://www29.a8.net/svt/bgt?aid=170621988234&wid=001&eno=01&mid=s00000009132001061000&mc=1">
    </a>
    <img border="0" width="1" height="1" src="https://www10.a8.net/0.gif?a8mat=2TL0RO+3VBGC2+1YGO+6BEQ9" alt="">
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%
     set_meta_tags :site => '厳選ハンバーガーマガジン',
                   :description => '厳選ハンバーガーを紹介するグルメナビサイト。各地域で美味しいハンバーガーをランキングし、値段や地図に加えておしゃれさや店員の態度などの情報を提供。',
                   :keywords => 'ハンバーガー, humberger, HUMNAVI, 池袋, Ikebukuro, グルメ, 厳選, 厳選ハンバーガー',
                   :canonical => request.original_url,
                   :reverse => true
    %>
    <%= display_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//www.google.com/jsapi', 'chartkick' %>
    <%= javascript_include_tag '//maps.google.com/maps/api/js?v=3.13&key=AIzaSyDXoULvL5Mjma3g18feLkLoRgO3Hx2j0zk&amp;libraries=geometry' %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>